package pojos;
// Generated Dec 26, 2016 4:32:17 PM by Hibernate Tools 4.3.1

import java.util.Date;


/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer id;
     private Guests guests;
     private Treatment treatment;
     private Users users;
     private String date;

    public Event() {
    }
    
    public Event(Guests guests, Treatment treatment, Users users, String date) {
       this.guests = guests;
       this.treatment = treatment;
       this.users = users;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Guests getGuests() {
        return this.guests;
    }
    
    public void setGuests(Guests guests) {
        this.guests = guests;
    }
    public Treatment getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(Treatment treatment) {
        this.treatment = treatment;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    @Override
    public String toString() {
        return users.getName() + ", " + guests.getName() + ", " + treatment.getType() + ", " + date;
    }




}


