package pojos;
// Generated Dec 26, 2016 4:32:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Guests generated by hbm2java
 */
public class Guests  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String name;
     private String phone;
     private String email;
     private Boolean buda;
     private Boolean pest;
     private Boolean rendszeres;
     private Boolean alkalmi;
     private Set<Event> events = new HashSet<Event>(0);

    public Guests() {
    }

    public Guests(Users users, String name, String phone, String email, Boolean buda, Boolean pest, Boolean rendszeres, Boolean alkalmi, Set<Event> events) {
       this.users = users;
       this.name = name;
       this.phone = phone;
       this.email = email;
       this.buda = buda;
       this.pest = pest;
       this.rendszeres = rendszeres;
       this.alkalmi = alkalmi;
       this.events = events;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        if (phone!=null){
            return this.phone;
        }else return "-";
        
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        if(email!=null){
        return this.email;
    }else return "-";
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getBuda() {
        return this.buda;
    }
    
    public void setBuda(Boolean buda) {
        this.buda = buda;
    }
    public Boolean getPest() {
        return this.pest;
    }
    
    public void setPest(Boolean pest) {
        this.pest = pest;
    }
    public String getPestiE(){
        if (pest && !buda){
            return "Pest";
        }else if(pest && buda){
            return "Pest + Buda";
        }else if(!pest && buda){
            return "Buda";
        }else return "-";
    }
    public Boolean getRendszeres() {
        return this.rendszeres;
    }
    
    public void setRendszeres(Boolean rendszeres) {
        this.rendszeres = rendszeres;
    }
    public String getRendszeresE(){
        if(rendszeres && !alkalmi){
            return "Permanent";
        }else if(rendszeres && alkalmi){
            return "?";
        }else if(!rendszeres && alkalmi){
            return "Alkalmi";
        }else return "-";
    }
    
    public Boolean getAlkalmi() {
        return this.alkalmi;
    }
    
    public void setAlkalmi(Boolean alkalmi) {
        this.alkalmi = alkalmi;
    }
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }
    
    @Override
    public String toString() {
        return name;
    }
    

}


