package pojos;
// Generated Dec 26, 2016 4:32:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Treatment generated by hbm2java
 */
public class Treatment  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String type;
     private Integer price;
     private Integer time;
     private Set<Event> events = new HashSet<Event>(0);

    public Treatment() {
    }

    public Treatment(Users users, String type, Integer price, Integer time, Set<Event> events) {
       this.type = type;
       this.price = price;
       this.time = time;
       this.events = events;
    }

    public Treatment(String type, Integer price, Integer time) {
        this.type = type;
        this.price = price;
        this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Users getUsers() {
        return users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }
    
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getTime() {
        return this.time;
    }
    
    public void setTime(Integer time) {
        this.time = time;
    }
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }

    @Override
    public String toString() {
        return type;
    }




}


