package pojos;
// Generated Dec 26, 2016 4:32:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private String username;
     private String email;
     private Set<Event> events = new HashSet<>(0);
     private Set<Guests> guestses = new HashSet<>(0);
     private Set<Treatment> treatments = new HashSet<>(0);
     
    public Users() {
    }

    public Users(String name, String password, String username, String email) {
        this.name = name;
        this.password = password;
        this.username = username;
        this.email = email;
    }

    public Users(String name, String password, String username, String email, Set<Event> events, Set<Guests> guestses) {
       this.name = name;
       this.password = password;
       this.username = username;
       this.email = email;
       this.events = events;
       this.guestses = guestses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }
    public Set<Guests> getGuestses() {
        return this.guestses;
    }
    
    public void setGuestses(Set<Guests> guestses) {
        this.guestses = guestses;
    }

    public Set<Treatment> getTreatments() {
        return treatments;
    }

    public void setTreatments(Set<Treatment> treatments) {
        this.treatments = treatments;
    }

    @Override
    public String toString() {
        return name;
    }




}


